
import type { Metadata } from 'next';
import '@/app/styles/globals.css';
import { BookingProvider } from '@/context/bookingContext';


// const roboto = Roboto({
//   variable: '--font-roboto',
//   weight: '500'
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <BookingProvider>
        {children}
        </BookingProvider>
  );
}
