import type { Metadata } from 'next';
import '@/app/globals.css';
import { Toaster } from 'react-hot-toast';

// const roboto = Roboto({
//   variable: '--font-roboto',
//   weight: '500'
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      {children}
    </>
  );
}
