
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import '@/app/styles/globals.css';
import Navigation from '@/components/Navigation';
import { SessionProvider } from 'next-auth/react';


const roboto = Roboto({
  variable: '--font-roboto',
  weight: '500'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        <SessionProvider>
        <Navigation />
        {children}
        </SessionProvider>
      </body>
    </html>
  );
}
