
import type { Metadata } from 'next';
import '@/app/globals.css';
import Navigation from '@/components/Navigation';
import {SessionProvider } from 'next-auth/react';
import { TooltipProvider } from '@radix-ui/react-tooltip';
import Footer from '@/components/Footer';


// const roboto = Roboto({
//   variable: '--font-roboto',
//   weight: '500'
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <SessionProvider>
        <TooltipProvider>
        <Navigation />
        {children}
        <Footer />
        </TooltipProvider>
        </SessionProvider>
  );
}
