
import type { Metadata } from 'next';
import '@/app/styles/globals.css';
import Navigation from '@/components/Navigation';
import {SessionProvider } from 'next-auth/react';
import { TooltipProvider } from '@radix-ui/react-tooltip';


// const roboto = Roboto({
//   variable: '--font-roboto',
//   weight: '500'
// });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <SessionProvider>
        <TooltipProvider>
        <Navigation />
        {children}
        </TooltipProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
